const SYMBOLS = {
  DEGREES: "°C",
  FAHRENHEIT: "°F",
};

const TIME_FORMAT = "p";
const SHORT_DATE_FORMAT = "d/M/yyyy";
const VALID_DATE_FORMAT = "yyyy-MM-dd";
const LONG_DATE_TIME_FORMAT = `${SHORT_DATE_FORMAT} - ${TIME_FORMAT}`;
const LONG_DATE_FORMAT = "EEEE, do MMMM yyyy";

export {
  SYMBOLS,
  TIME_FORMAT,
  SHORT_DATE_FORMAT,
  VALID_DATE_FORMAT,
  LONG_DATE_TIME_FORMAT,
  LONG_DATE_FORMAT,
};
